name: mebel_uz
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  flutter_svg: ^2.0.10+1
  sizer: ^2.0.15
  flutter_animated_icons: ^1.0.1
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.2
  firebase_auth: ^4.19.2
  get: ^4.6.6
  connectivity: ^3.0.6
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.2.2+5
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  autoscale_tabbarview: ^1.0.2
  url_launcher: ^6.2.6
  get_storage: ^2.1.1
  http: ^1.2.1
  badges: ^3.1.2
  device_info_plus: ^10.1.0
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
